module.exports = {
  apps: [
    {
      name: 'amexing-api',
      script: './src/index.js',
      instances: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? 'max' : 1,
      exec_mode: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? 'cluster' : 'fork',
      watch: process.env.NODE_ENV === 'development',
      ignore_watch: [
        'node_modules',
        'logs',
        '.git',
        'coverage',
        '.nyc_output',
        'tmp',
        'uploads',
        'sessions',
      ],
      env: {
        NODE_ENV: 'development',
        PORT: 1337,
      },
      env_staging: {
        NODE_ENV: 'staging',
        PORT: 1337,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 1338,
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_file: './logs/pm2-combined.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
      shutdown_with_message: false,
    },
    {
      name: 'amexing-dashboard',
      script: 'parse-dashboard',
      args: '--config ./config/parse-dashboard.js',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      env: {
        NODE_ENV: 'development',
        PORT: 4040,
      },
      env_staging: {
        NODE_ENV: 'staging',
        PORT: 4040,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4040,
      },
      error_file: './logs/dashboard-error.log',
      out_file: './logs/dashboard-out.log',
      log_file: './logs/dashboard-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 5,
    },
  ],

  deploy: {
    production: {
      user: 'deploy',
      host: 'your-production-server.com',
      ref: 'origin/main',
      repo: 'git@github.com:your-org/amexing-web.git',
      path: '/var/www/amexing-web',
      'pre-deploy-local': 'yarn test',
      'post-deploy': 'yarn install && pm2 reload ecosystem.config.js --env production',
      'pre-setup': '',
      env: {
        NODE_ENV: 'production',
      },
    },
    staging: {
      user: 'deploy',
      host: 'your-staging-server.com',
      ref: 'origin/develop',
      repo: 'git@github.com:your-org/amexing-web.git',
      path: '/var/www/amexing-web-staging',
      'post-deploy': 'yarn install && pm2 reload ecosystem.config.js --env production',
      env: {
        NODE_ENV: 'staging',
      },
    },
  },
};