name: 🔒 Security Vulnerability
description: Report a security vulnerability (PCI DSS Compliance)
title: "[SECURITY] Brief description of vulnerability"
labels: ["security", "vulnerability", "priority-high"]
assignees: ["security-team"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **IMPORTANT**: This form is for reporting security vulnerabilities. For sensitive issues, please email security@meeplab.com instead.
        
        This project follows PCI DSS 4.0 compliance standards. All security reports are treated with highest priority.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical (System compromise, data breach potential)
        - High (Significant security impact)
        - Medium (Moderate security risk)
        - Low (Minor security issue)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Input Validation (XSS, SQL Injection)
        - Data Exposure/Leakage
        - Cryptographic Issue
        - Session Management
        - Dependency Vulnerability
        - Configuration Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the security vulnerability
      placeholder: |
        - What is the vulnerability?
        - How can it be exploited?
        - What data/systems are affected?
      value: |
        ## Vulnerability Details
        
        ### Description
        [Describe the vulnerability]
        
        ### Potential Impact
        [What could an attacker achieve?]
        
        ### Affected Components
        [Which parts of the system are affected?]
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the vulnerability
      placeholder: |
        1. Navigate to...
        2. Enter payload...
        3. Observe result...
      value: |
        ## Reproduction Steps
        
        1. 
        2. 
        3. 
        
        ### Expected Behavior
        [What should happen?]
        
        ### Actual Behavior
        [What actually happens?]
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: System information where vulnerability was discovered
      placeholder: |
        - Browser/Client: 
        - Operating System: 
        - Application Version:
      value: |
        - **Browser**: 
        - **OS**: 
        - **Version**: 
        - **Environment**: [Development/Staging/Production]
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept (Optional)
      description: Include proof of concept code/screenshots if available
      placeholder: |
        ```javascript
        // Proof of concept code
        ```
        
        Or attach screenshots showing the vulnerability

  - type: checkboxes
    id: checklist
    attributes:
      label: Security Checklist
      description: Please confirm the following
      options:
        - label: I have verified this is a legitimate security issue
          required: true
        - label: I have not disclosed this vulnerability publicly
          required: true
        - label: I understand this will be handled according to our security policy
          required: true
        - label: I have checked that this hasn't been reported before
          required: true

  - type: markdown
    attributes:
      value: |
        ## 📞 Contact Information
        
        For **critical vulnerabilities** or **sensitive issues**, please email: **security@meeplab.com**
        
        **Response Timeline**:
        - Critical: 24-48 hours
        - High: 72 hours  
        - Medium/Low: 1 week
        
        Thank you for helping keep AmexingWeb secure! 🛡️