/**
 * Secrets Manager - Secure handling of environment variables and secrets.
 * Provides encryption, decryption, and secure access to sensitive configuration.
 */

const crypto = require('crypto');
const fs = require('fs');

/**
 * SecureSecretsManager class for handling encrypted environment variables.
 */
class SecureSecretsManager {
  constructor() {
    this.encryptedSecrets = new Map();
    this.loadedSecrets = new Set();
    this.algorithm = 'aes-256-gcm';
    this.keyLength = 32;
  }

  /**
   * Initialize the secrets manager with encryption key.
   * @param {string} encryptionKey - Base64 encoded encryption key.
   * @example
   * const manager = new SecureSecretsManager();
   * manager.initialize(process.env.ENCRYPTION_KEY);
   */
  initialize(encryptionKey) {
    if (!encryptionKey) {
      throw new Error('Encryption key is required for secrets manager');
    }

    try {
      this.encryptionKey = Buffer.from(encryptionKey, 'base64');
      if (this.encryptionKey.length !== this.keyLength) {
        throw new Error(
          `Encryption key must be ${this.keyLength} bytes when decoded`
        );
      }
    } catch (error) {
      throw new Error(`Invalid encryption key format: ${error.message}`);
    }
  }

  /**
   * Encrypt a secret value.
   * @param {string} value - Plain text value to encrypt.
   * @returns {string} Encrypted value with IV and auth tag.
   * @example
   * const encrypted = manager.encryptSecret('my-secret-value');
   */
  encryptSecret(value) {
    if (!this.encryptionKey) {
      throw new Error('Secrets manager not initialized');
    }

    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv(
      this.algorithm,
      this.encryptionKey,
      iv
    );
    cipher.setAAD(Buffer.from('secrets-manager'));

    let encrypted = cipher.update(value, 'utf8', 'hex');
    encrypted += cipher.final('hex');

    const authTag = cipher.getAuthTag();

    return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted}`;
  }

  /**
   * Decrypt a secret value.
   * @param {string} encryptedValue - Encrypted value with IV and auth tag.
   * @returns {string} Decrypted plain text value.
   * @example
   * const decrypted = manager.decryptSecret(encryptedValue);
   */
  decryptSecret(encryptedValue) {
    if (!this.encryptionKey) {
      throw new Error('Secrets manager not initialized');
    }

    try {
      const [ivHex, authTagHex, encrypted] = encryptedValue.split(':');

      if (!ivHex || !authTagHex || !encrypted) {
        throw new Error('Invalid encrypted value format');
      }

      const iv = Buffer.from(ivHex, 'hex');
      const authTag = Buffer.from(authTagHex, 'hex');

      const decipher = crypto.createDecipheriv(
        this.algorithm,
        this.encryptionKey,
        iv
      );
      decipher.setAAD(Buffer.from('secrets-manager'));
      decipher.setAuthTag(authTag);

      let decrypted = decipher.update(encrypted, 'hex', 'utf8');
      decrypted += decipher.final('utf8');

      return decrypted;
    } catch (error) {
      throw new Error(`Failed to decrypt secret: ${error.message}`);
    }
  }

  /**
   * Load and decrypt secrets from encrypted environment file.
   * @param {string} filePath - Path to encrypted secrets file.
   * @returns {object} Decrypted environment variables.
   * @example
   * const secrets = manager.loadEncryptedEnv('.env.vault');
   */
  loadEncryptedEnv(filePath) {
    try {
      // eslint-disable-next-line security/detect-non-literal-fs-filename
      const encryptedContent = fs.readFileSync(filePath, 'utf8');
      const secrets = {};

      encryptedContent.split('\n').forEach((line) => {
        const trimmedLine = line.trim();
        if (trimmedLine && !trimmedLine.startsWith('#')) {
          const [key, encryptedValue] = trimmedLine.split('=', 2);
          if (key && encryptedValue) {
            secrets[key.trim()] = this.decryptSecret(encryptedValue.trim());
            this.loadedSecrets.add(key.trim());
          }
        }
      });

      return secrets;
    } catch (error) {
      throw new Error(`Failed to load encrypted environment: ${error.message}`);
    }
  }

  /**
   * Save encrypted secrets to file.
   * @param {object} secrets - Plain text secrets to encrypt and save.
   * @param {string} filePath - Path to save encrypted secrets.
   * @example
   * manager.saveEncryptedEnv(secrets, '.env.vault');
   */
  saveEncryptedEnv(secrets, filePath) {
    try {
      const lines = [];
      lines.push('# Encrypted Environment Variables');
      lines.push('# Generated by SecureSecretsManager');
      lines.push(`# Created: ${new Date().toISOString()}`);
      lines.push('');

      Object.entries(secrets).forEach(([key, value]) => {
        if (typeof key === 'string' && typeof value === 'string') {
          const encryptedValue = this.encryptSecret(value);
          lines.push(`${key}=${encryptedValue}`);
        }
      });

      // eslint-disable-next-line security/detect-non-literal-fs-filename
      fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
    } catch (error) {
      throw new Error(`Failed to save encrypted environment: ${error.message}`);
    }
  }

  /**
   * Securely get a secret value, clearing it from memory after access.
   * @param {string} key - Secret key name.
   * @param {object} secrets - Secrets object.
   * @returns {string} Secret value.
   * @example
   * const secret = manager.getSecureValue('DATABASE_PASSWORD', secrets);
   */
  getSecureValue(key, secrets) {
    // Validate key to prevent object injection
    if (
      typeof key !== 'string'
      || key.includes('__proto__')
      || key.includes('constructor')
      || key.includes('prototype')
    ) {
      return undefined;
    }

    // eslint-disable-next-line security/detect-object-injection
    const value = secrets[key];
    if (value) {
      // Mark as accessed for audit purposes
      this.encryptedSecrets.set(key, {
        accessed: new Date(),
        accessCount: (this.encryptedSecrets.get(key)?.accessCount || 0) + 1,
      });
    }
    return value;
  }

  /**
   * Clear secrets from memory for security.
   * @param {object} secretsObj - Secrets object to clear.
   * @returns {object} Cleared secrets object.
   * @example
   * const cleared = manager.clearSecrets(secrets);
   */
  clearSecrets(secretsObj) {
    const secretsCopy = { ...secretsObj };
    Object.keys(secretsCopy).forEach((key) => {
      // Validate key to prevent object injection
      if (
        typeof key === 'string'
        && !key.includes('__proto__')
        && !key.includes('constructor')
        && !key.includes('prototype')
      ) {
        // eslint-disable-next-line security/detect-object-injection
        secretsCopy[key] = null;
        // eslint-disable-next-line security/detect-object-injection
        delete secretsCopy[key];
      }
    });
    return secretsCopy;
  }

  /**
   * Generate a secure random secret.
   * @param {number} length - Length of secret to generate.
   * @param {object} options - Generation options.
   * @returns {string} Generated secret.
   * @example
   * const secret = manager.generateSecret(32, { encoding: 'base64' });
   */
  generateSecret(length = 32, options = {}) {
    const { encoding = 'base64', charset = 'alphanumeric' } = options;

    if (charset === 'alphanumeric') {
      const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
      let result = '';
      for (let i = 0; i < length; i += 1) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
      }
      return result;
    }

    const bytes = crypto.randomBytes(length);
    return encoding === 'hex'
      ? bytes.toString('hex')
      : bytes.toString('base64');
  }

  /**
   * Generate an encryption key for the secrets manager.
   * @returns {string} Base64 encoded encryption key.
   * @example
   * const key = SecureSecretsManager.generateEncryptionKey();
   */
  static generateEncryptionKey() {
    return crypto.randomBytes(32).toString('base64');
  }

  /**
   * Validate environment variables against required schema.
   * @param {object} secrets - Secrets to validate.
   * @param {object} schema - Required environment schema.
   * @returns {object} Validation result.
   * @example
   * const result = manager.validateSecrets(secrets, requiredSchema);
   */
  validateSecrets(secrets, schema) {
    const missing = [];
    const invalid = [];

    // eslint-disable-next-line complexity
    Object.entries(schema).forEach(([key, requirements]) => {
      // Validate key to prevent object injection
      if (
        typeof key !== 'string'
        || key.includes('__proto__')
        || key.includes('constructor')
        || key.includes('prototype')
      ) {
        return;
      }
      // eslint-disable-next-line security/detect-object-injection
      const value = secrets[key];

      if (!value) {
        missing.push(key);
        return;
      }

      if (requirements.minLength && value.length < requirements.minLength) {
        invalid.push(`${key}: minimum length ${requirements.minLength}`);
      }

      if (requirements.pattern && !requirements.pattern.test(value)) {
        invalid.push(`${key}: does not match required pattern`);
      }
    });

    return {
      valid: missing.length === 0 && invalid.length === 0,
      missing,
      invalid,
    };
  }

  /**
   * Get audit information about secret access.
   * @returns {object} Audit information.
   * @example
   * const audit = manager.getAuditInfo();
   */
  getAuditInfo() {
    const audit = {
      loadedSecrets: Array.from(this.loadedSecrets),
      accessedSecrets: {},
      timestamp: new Date().toISOString(),
    };

    this.encryptedSecrets.forEach((info, key) => {
      // Validate key to prevent object injection
      if (
        typeof key === 'string'
        && !key.includes('__proto__')
        && !key.includes('constructor')
        && !key.includes('prototype')
      ) {
        // eslint-disable-next-line security/detect-object-injection
        audit.accessedSecrets[key] = info;
      }
    });

    return audit;
  }
}

// Singleton instance
let instance = null;

/**
 * Get the singleton secrets manager instance.
 * @returns {SecureSecretsManager} Secrets manager instance.
 * @example
 * const manager = getSecretsManager();
 */
function getSecretsManager() {
  if (!instance) {
    instance = new SecureSecretsManager();
  }
  return instance;
}

module.exports = {
  SecureSecretsManager,
  getSecretsManager,
};
